### ISSUE TITLE
Improve interface

### ISSUE THREAD

**Issue by AnthonyLim23** [mantidproject/quasielasticbayes#29]
The current version will have specific calls for QLdata in Python and Fortran. This is to investigate a method (possibly using a config file) to wrap both methods with into a single function and to then have a way of changing which version (Python or Fortran) to run. Initially this will default to Fortran.

**Comment by martyngigg** [comment]
It will be nice to have the ability to switch. Do you see that has something long term or short lived for validation?

I would also suggest considering an environment variable as they are easier to apply on a per-process basis if you wanted to do a side-by-side comparison for example.

An example of this in CaChannel: https://github.com/CaChannel/CaChannel/blob/master/src/CaChannel/ca.py#L4

**Comment by AnthonyLim23** [comment]
should also change the module names to be of the style:
quasielasticbayes.c_python.four
quasielasticbayes.fortran.four
